services:
  rtmp:
    image: fixwad-registry.setidaknya.my.id/rtmp:latest
    container_name: rtmp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"
      - "8100:8080"
    restart: always
    volumes:
      - ./data/hls:/opt/data/hls
